### PR TITLE
Set Up GitHub Runner with Terraform

### PR DESCRIPTION
**Pull request by mandy2666**

### CODE REVIEW

**Review by cobycloud — CHANGES_REQUESTED** [review]
use github env secrets for credentials within the workflow.

**Comment by cobycloud** [comment]
https://registry.terraform.io/providers/TelkomIndonesia/linux/latest/docs

**Comment by mandy2666** [comment]
made changes in main.tf file and added GitHub env secrets for credentials within the workflow file

**Review by cobycloud — CHANGES_REQUESTED** [review]
please ensure the github and tf use github env vars for the credentials
please also use a env var for: ip address, port, user, and password

**Comment by mandy2666** [comment]
added GitHub env

**Review by cobycloud — CHANGES_REQUESTED** [review]
missing an env var

**Comment by cobycloud** [comment]
also, please remove aws vars

**Comment by mandy2666** [comment]
I have removed aws env vars and added some env's please review it

**Pull request merged**
